# This rule is not used by the project nango-integration-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over nango.nango.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nango-integration-operator
    app.kubernetes.io/managed-by: kustomize
  name: nangointegration-admin-role
rules:
- apiGroups:
  - nango.nango.dev
  resources:
  - nangointegrations
  verbs:
  - '*'
- apiGroups:
  - nango.nango.dev
  resources:
  - nangointegrations/status
  verbs:
  - get
