---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nango.nango.dev
  resources:
  - nangointegrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nango.nango.dev
  resources:
  - nangointegrations/finalizers
  verbs:
  - update
- apiGroups:
  - nango.nango.dev
  resources:
  - nangointegrations/status
  verbs:
  - get
  - patch
  - update
