# Example secrets for the Nango Integration Operator
# 
# IMPORTANT: Replace the base64-encoded values with your actual credentials
# You can encode values using: echo -n "your-value" | base64

---
# Secret for OAuth credentials
apiVersion: v1
kind: Secret
metadata:
  name: slack-oauth-secret
  namespace: default
type: Opaque
data:
  # Replace with your actual Slack OAuth client ID (base64 encoded)
  client_id: eW91ci1zbGFjay1jbGllbnQtaWQ=  # "your-slack-client-id"
  # Replace with your actual Slack OAuth client secret (base64 encoded)
  client_secret: eW91ci1zbGFjay1jbGllbnQtc2VjcmV0  # "your-slack-client-secret"

---
# Secret for Nango API token
apiVersion: v1
kind: Secret
metadata:
  name: nango-api-secret
  namespace: default
type: Opaque
data:
  # Replace with your actual Nango API token (base64 encoded)
  token: eW91ci1uYW5nby1hcGktdG9rZW4=  # "your-nango-api-token"

---
# Example NangoIntegration that uses the secrets with the new structure
apiVersion: nango.nango.dev/v1alpha1
kind: NangoIntegration
metadata:
  name: slack-integration-with-secrets
  namespace: default
spec:
  unique_key: "slack-with-secrets"
  provider: "slack"
  display_name: "Slack Integration (Secure)"
  credentials:
    type: "OAUTH1"
    client_id:
      secretKeyRef:
        name: "slack-oauth-secret"
        key: "client_id"
    client_secret:
      secretKeyRef:
        name: "slack-oauth-secret"
        key: "client_secret"
    scopes: "chat:write,channels:read,users:read"
  nango_token:
    secretKeyRef:
      name: "nango-api-secret"
      key: "token"
  nango_base_url: "https://api.nango.dev" 